- name: Create security group
  ec2_group:
    name: "{{ security_group }}"
    description: "Sec group for app"
    region: "{{ region }}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    rules:
    - proto: tcp
      ports:
        - 22
      cidr_ip: 0.0.0.0/0
      rule_desc: allow all on ssh port
  register: basic_firewall

- name: Provision instance(s)
  ec2:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    keypair: "{{ keypair }}"
    group_id: "{{ basic_firewall.group_id }}"
    image: "{{ image }}"
    instance_type: t2.micro
    region: "{{ region }}"
    wait: true
    count: "{{ count }}"
  register: ec2

- name: Adding the instance to the inventory temp
  add_host: name={{ item.public_ip }} groups=dev-new
  with_items: "{{ ec2.instances }"

- name: Adding the instance created in the host file
  local_action: lineinfil
    dest="./hosts"
    regexp={{ item.public_ip }}
    insertafter="[dev]" line={{ item.public_ip }}
  with_items: "{{ ec2.instances }}"

- name: Waiting ssh
  local_action: wait_for
    host={{ item.public_ip }}
    port=22
    state=started
  with_items: "{{ ec2.instances }}" 

- name: Adding a name tag to the instance
  local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      Name: DEV environment
- name: Adding the machine created in known_hosts
  shell: ssh-keyscan -H {{ item.public_ip }} >> ~/.ssh/known_hosts
  with_items: "{{ ec2.instances }}"
